import Head from 'next/head'
import { useRouter } from 'next/router'
import { getCookie } from '../componets/utiles/cookie';


export default function Home() {
  const router =useRouter();
  const token = getCookie("token");
  if(token){return router.push("/products")}
  else{
    router.push("/login")
  }
  return (
    <>
      <Head>
        <title>Panel Admin Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/amazon.svg" />
      </Head>
      
      
    </>
  )
}
